/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-05-16 17:54:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--navigation------------>\r\n");
      out.write("<nav>\r\n");
      out.write("    <!--logo c?a web (hi?n ? ??u trang)   -->\r\n");
      out.write("    <link rel=\"stylesheet\" href = \"css/headerstyle.css\"/>\r\n");
      out.write("    <a href=\"home\" class=\"logo\">\r\n");
      out.write("        <img src=\"images/logo.jpg\" alt=\"alt\"/>\r\n");
      out.write("    </a>\r\n");
      out.write("    <!--menu--->\r\n");
      out.write("    <ul class=\"menu\">\r\n");
      out.write("        <li><a href=\"BXH\">Xếp Hạng</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"Video-Clip\">Video</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"Song?page=1\">Bài Hát</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"#\">Nghệ Sĩ</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"#\">Anime</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"#\">Tiktok</a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    <!--search icon-->\r\n");
      out.write("    <!--search------->\r\n");
      out.write("    <div class=\"search-box\">\r\n");
      out.write("        <div class=\"search\">\r\n");
      out.write("            <span class=\"material-icons\" id=\"searchicon\">search</span>\r\n");
      out.write("            <form action=\"#\" method=\"get\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"nhập bài hát,video, tên nghệ sĩ\" id = \"searchinput\" onkeydown=\"startSearch()\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"results\">\r\n");
      out.write("            <ul id=\"list\">\r\n");
      out.write("                <li><a href=\"\">hi</a></li>\r\n");
      out.write("                <li><a href=\"\">hi</a></li>\r\n");
      out.write("                <li><a href=\"\">hi</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Đăng nhập && Đăng kí -->\r\n");
      out.write("    <div class=\"Register\" id=\"register\">\r\n");
      out.write("        ");

        String username= (String) session.getAttribute("username");
        
        Cookie cookie = null;
        Cookie[] cookies = null;
        cookies = request.getCookies();
        boolean flag =false;
        
        if (cookies != null) {
            for (int i = 0; i < cookies.length; i++) {
                cookie = cookies[i];
                if ((cookie.getName()).compareTo("lastname") == 0){
                    flag=true;
                    
      out.write("\r\n");
      out.write("                    <p>Welcome, ");
      out.print(cookie.getValue());
      out.write("</p>\r\n");
      out.write("                    <a href=\"LogOut\">Đăng Xuất</a>\r\n");
      out.write("                    ");

                }
            }
        }
        if(session.getAttribute("username")!=null && !flag){
        
      out.write("\r\n");
      out.write("            <p>Welcome, ");
      out.print( session.getAttribute("username"));
      out.write("</p>\r\n");
      out.write("                    <a href=\"LogOut\">Đăng Xuất</a>\r\n");
      out.write("        ");
}
            else if(!flag){
        
      out.write("\r\n");
      out.write("            <a href=\"signin_signup.jsp\">Đăng Nhập</a><a>/</a><a href=\"signin_signup.jsp\">Đăng Ký</a>\r\n");
      out.write("        ");
 }
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"JS/LiveSearch.js\"></script>\r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
