/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-05-16 17:54:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class slideshow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href = \"css/slideshow.css\"/>\r\n");
      out.write("<div class = \"container\" id =\"container\">\r\n");
      out.write("  <div class = \"inner\">\r\n");
      out.write("    <div class = \"track\" id =\"track\">\r\n");
      out.write("        ");

            for(int i=0;i<10;i++){
            
      out.write("\r\n");
      out.write("            <div class = \"card-container\">\r\n");
      out.write("              <div class= \"card\">\r\n");
      out.write("                  ");

                      String link = "window.location.href='/Nhachayvjppro/mp3?songid="+request.getAttribute("songid"+Integer.toString(i))+"'";
                  
      out.write("\r\n");
      out.write("                  <img src=");
      out.print(request.getAttribute("imagelink"+Integer.toString(i)));
      out.write(" alt=\"\" onclick=");
      out.print(link);
      out.write("></img>\r\n");
      out.write("                <!-- button play -->\r\n");
      out.write("                <div class=\"play\">\r\n");
      out.write("                    <a href=\"/Nhachayvjppro/mp3?songid=");
      out.print(request.getAttribute("songid"+Integer.toString(i)));
      out.write("\">\r\n");
      out.write("                      <span class=\"material-icons\">\r\n");
      out.write("                        play_circle_outline\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"hidden\" name=\"songnameslideshow\" size=\"20\" value=\"");
      out.print(request.getAttribute("songname"+Integer.toString(i)));
      out.write("\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"artistslideshow\" size=\"20\" value=\"");
      out.print(request.getAttribute("artistname"+Integer.toString(i)));
      out.write("\" />\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                    <a href=\"/Nhachayvjppro/mp3?songid=");
      out.print(request.getAttribute("songid"+Integer.toString(i)));
      out.write('"');
      out.write('>');
      out.print(request.getAttribute("songname"+Integer.toString(i)));
      out.write("</a> - <a href=\"artist?artistid=");
      out.print(request.getAttribute("artist1id"+Integer.toString(i)));
      out.write("&songpage=1&videopage=1\">");
      out.print(request.getAttribute("artistname"+Integer.toString(i)));
      out.write("</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
}
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class = \"outer\">\r\n");
      out.write("    <div class=\"navi\">\r\n");
      out.write("      <button id =\"prev\" class=\"prev\">\r\n");
      out.write("        <span class=\"material-icons\">\r\n");
      out.write("        keyboard_arrow_left\r\n");
      out.write("        </span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <button id =\"next\" class=\"next\">\r\n");
      out.write("        <span class=\"material-icons\">\r\n");
      out.write("        keyboard_arrow_right\r\n");
      out.write("        </span>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
